name: dotnet-docker-heroku CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_TEST }}
  APP_NAME: ${{ 'net-deploy-test' }}

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create image
      run: docker build -t apiproject -f src/API/Dockerfile .

    # Build Docker image
    - name: Docker build
      run: |
        docker login --username=otash_baxadirov@mail.ru --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        docker tag apiproject registry.heroku.com/$APP_NAME/web
        docker push registry.heroku.com/$APP_NAME/web
        heroku container:release web -a $APP_NAME